# -*- coding: utf-8 -*-
"""作業1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a37UajM6Yg4BRlIkU-PUCLcfOtkSvfoV
"""

def decimal_to_binary(num):
    binary = ""
    for _ in range(8):  # 8位二進位,因為255以下的數字只有8位數
        binary = str(num % 2) + binary # % 取餘數
        num // 2 # // 取商數
    return binary

def decimal_to_hex(num):
    hex_digits = "0123456789ABCDEF"
    hex_result = ""
    for _ in range(2):  # 兩位十六進位
        hex_result = hex_digits[num % 16] + hex_result
        num //= 16
    return hex_result

def convert_number():
    try:
        num = int(input("請輸入0到255之間的數字: "))
        if 0 <= num <= 255:
            print(f"二進位: {decimal_to_binary(num)}")
            print(f"十六進位: {decimal_to_hex(num)}")
        else:
            print("請輸入0到255之間的數字!")
    except ValueError:
        print("請輸入有效的整數!")

convert_number()